### ISSUE TITLE
Only 4 apps are shown when using search bar, and no stream showing up in search results

### ISSUE THREAD

**Issue by mountaindude** [countnazgul/sense-custom-hub#1]
Love the extension - great concept!
Seems the search-as-you-type box has an issue though, or maybe it's by design (have to admit I haven't looked into it... wanted to mention it here first).

Let's say I have 20 development versions of apps, each with a DEV suffix. 
I.e. "App 1 DEV", "App 2 DEV" etc.
Typing "DEV" in the search box shows me 4 of those 20 apps.

Similar issue with streams - no streams show up when searching. 

Tested on Sense Enterprise 3.1 SR3, btw. 

Will digg into things a bit if I can find time here.

**Comment by countnazgul** [comment]
Don't bother to look into the code ... yet. I'm re-writing(ish) it at the moment. Need to make the code more "readable" and will migrate the code to use vue.js 
Planning to have a nice and productive holiday :)

**Comment by mountaindude** [comment]
Yeah those holidays are nice!

I have been toying with a related idea, from another angle. 
I have written some node.js code to that gets a list of all apps that have a custom property IsTemplate set to yes. Another API endpoint in the node code then creates a new app based on the template, and finally sets desired person as owner. 

The idea is to lower the barrier of entry for new sense developers. 
No UI for my code yet, but coupled with your simplified hub it would be pretty slick... I'll put it up on github during coming days.
